name: Go

on:
  push:
    branches: [master, v8, v9]
  pull_request:
    branches: [master, v8, v9]

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.18.x, 1.19.x]

    steps:
      - name: Set up ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: |
          go vet ./...
          go test ./...
          go test ./... -short -race
          go test ./... -run=NONE -bench=. -benchmem
